---
######################################
# ANSIBLE PLAYBOOK FOR WG INSTALLING #
######################################


- name: "Install Wireguard"
  hosts: all
  remote_user: root

  vars_prompt:

  - name: "interface"
    prompt: "What interface should I use?"
    default: "eth0"
    private: no

  tasks:

  - name: "Install wireguard"
    ansible.builtin.apt:
      name: wireguard
      state: latest

  - name: "Install qrencode"
    ansible.builtin.apt:
      name: qrencode
      state: latest

  - name: "Create server keys"
    shell: wg genkey | tee /etc/wireguard/server.priv | wg pubkey > /etc/wireguard/server.pub
    args:
      executable: /bin/bash

  - name: "Create client keys"
    shell: wg genkey | tee /etc/wireguard/client.priv | wg pubkey > /etc/wireguard/client.pub
    args:
      executable: /bin/bash

  - name: Register client public key
    shell: cat /etc/wireguard/client.pub
    register: client_pub

  - name: Register client private key
    shell: cat /etc/wireguard/client.priv
    register: client_priv

  - name: Register server public key
    shell: cat /etc/wireguard/server.pub
    register: server_pub

  - name: Register server private key
    shell: cat /etc/wireguard/server.priv
    register: server_priv

  - name: "Get public IP address"
    get_url: 
      url: http://ifconfig.me
      http_agent: curl
      dest: /tmp/public_ip    

  - name: Register server public IP
    shell: cat /tmp/public_ip
    register: public_ip

  - name: "Create server config file"
    copy:
      dest: "/etc/wireguard/wg0.conf"
      content: |
          [Interface]
          PrivateKey = {{ server_priv.stdout }}
          Address = 10.0.0.1/24
          PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o {{ interface }} -j MASQUERADE; echo 1 > /proc/sys/net/ipv4/ip_forward
          PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o {{ interface }} -j MASQUERADE; echo 0 > /proc/sys/net/ipv4/ip_forward
          ListenPort = 51820


          [Peer]
          PublicKey = {{ client_pub.stdout }}
          AllowedIPs = 10.0.0.2/32

  - name: "Create client config file"
    copy:
      dest: "/etc/wireguard/client.conf"
      content: |
          [Interface]
          PrivateKey = {{ client_priv.stdout }}
          Address = 10.0.0.2/32
          DNS = 1.1.1.1
          
          
          [Peer]
          PublicKey = {{ server_pub.stdout }}
          AllowedIPs = 0.0.0.0/0
          Endpoint = {{ public_ip.stdout }}:51820 

  - name: "Start WireGuard"
    shell:
      cmd: systemctl start wg-quick@wg0
    args:
      executable: /bin/bash

  - name: "Enable WireGuard"
    shell:
      cmd: systemctl enable wg-quick@wg0
    args:
      executable: /bin/bash
          
